[package]
name = "echo_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.5.1", features = ["default"] }
clap = { version = "4.5.4", features = ["derive"] }
